"""Stable domain-model imports for the simulation."""

from simulation.domain.entities import Phase
from simulation.domain.inventory import (
    Inventory,
    ItemInstance,
    ItemTransferReceipt,
    ItemDefinition,
    PeerTradeOffer,
    PeerTradeReceipt,
    Shop,
    TradeMemory,
    TradeQuote,
    TradeReceipt,
)
from simulation.domain.campus import (
    BaseAttributes,
    CampusNPCRecord,
    CampusNPCProfile,
    DerivedStats,
    EmotionState,
    NeedState,
    NightAccess,
    PersonalityTraits,
    RelationshipDimensions,
    SimulationTier,
    derive_stats,
)
from simulation.domain.tasks import CampusTask, ForumKind, TaskState
from simulation.domain.events import EventDraft, SimulationEvent
from simulation.domain.chronicles import (
    CHRONICLE_CATEGORIES,
    CHRONICLE_PHASES,
    CHRONICLE_VISIBILITIES,
    NpcChronicleEntry,
    chronicle_dicts,
)
from simulation.domain.world_state import AGGREGATE_NAMES, ClockState, WorldState
from simulation.domain.combat import (
    COMBAT_ROWS,
    DEPLOYMENT_STATES,
    CombatDeploymentPolicy,
    CombatRoundPolicy,
    parse_combat_deployment_policy,
    parse_combat_round_policy,
)
from simulation.domain.action_economy import (
    ActionEconomyPolicy,
    PhaseActionRule,
    build_action_economy_policy,
)
from simulation.domain.activities import (
    ACTIVITY_CATEGORIES,
    EMOTION_NAMES,
    NEED_NAMES,
    CampusActivityDefinition,
    parse_activity_definition,
)
from simulation.domain.abilities import (
    ABILITY_SOURCE_KINDS,
    CARD_TARGETS,
    CARD_RANGE_PATTERNS,
    CARD_TYPES,
    CampusAbilityDefinition,
    CardBlueprint,
)
from simulation.domain.parties import CampusPartyPolicy, parse_party_policy
from simulation.domain.cognition import (
    BoundedDecisionRequest,
    BoundedDecisionResponse,
    BoundedDialogueRequest,
    BoundedDialogueResponse,
    CognitionPolicy,
)
from simulation.domain.schedules import (
    CampusScheduleTemplate,
    PlannedScheduleSlot,
    ScheduleSlotTemplate,
    parse_schedule_template,
)
from simulation.domain.locations import (
    CampusLocation,
    CampusLocationGraph,
    CampusPassage,
    CampusRegion,
    CampusRoute,
    EntranceStyle,
    InstancePolicy,
    InteriorTemplate,
    LocationKind,
    RouteStep,
    TransitionKind,
)

__all__ = [
    "BaseAttributes",
    "CampusNPCProfile",
    "CampusNPCRecord",
    "CampusTask",
    "DerivedStats",
    "EmotionState",
    "Inventory",
    "ItemInstance",
    "ItemTransferReceipt",
    "ItemDefinition",
    "NeedState",
    "NightAccess",
    "Phase",
    "PeerTradeOffer",
    "PeerTradeReceipt",
    "PersonalityTraits",
    "RelationshipDimensions",
    "Shop",
    "SimulationTier",
    "TradeMemory",
    "TradeQuote",
    "TradeReceipt",
    "ForumKind",
    "TaskState",
    "AGGREGATE_NAMES",
    "ActionEconomyPolicy",
    "ACTIVITY_CATEGORIES",
    "ABILITY_SOURCE_KINDS",
    "CARD_TARGETS",
    "CARD_RANGE_PATTERNS",
    "CARD_TYPES",
    "CampusAbilityDefinition",
    "CampusPartyPolicy",
    "BoundedDecisionRequest",
    "BoundedDecisionResponse",
    "BoundedDialogueRequest",
    "BoundedDialogueResponse",
    "CognitionPolicy",
    "CardBlueprint",
    "EMOTION_NAMES",
    "NEED_NAMES",
    "CampusActivityDefinition",
    "PhaseActionRule",
    "build_action_economy_policy",
    "parse_activity_definition",
    "parse_party_policy",
    "CampusScheduleTemplate",
    "PlannedScheduleSlot",
    "ScheduleSlotTemplate",
    "parse_schedule_template",
    "ClockState",
    "EventDraft",
    "SimulationEvent",
    "CHRONICLE_CATEGORIES",
    "CHRONICLE_PHASES",
    "CHRONICLE_VISIBILITIES",
    "NpcChronicleEntry",
    "chronicle_dicts",
    "WorldState",
    "COMBAT_ROWS",
    "DEPLOYMENT_STATES",
    "CombatDeploymentPolicy",
    "CombatRoundPolicy",
    "parse_combat_deployment_policy",
    "parse_combat_round_policy",
    "CampusLocation",
    "CampusLocationGraph",
    "CampusPassage",
    "CampusRegion",
    "CampusRoute",
    "EntranceStyle",
    "InstancePolicy",
    "InteriorTemplate",
    "LocationKind",
    "RouteStep",
    "TransitionKind",
    "derive_stats",
]
